<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Shree" name="com.testngexample.Sample6" tests="1" failures="0" timestamp="2020-04-23T07:17:27 IST" time="0.094" errors="1">
  <testcase name="test1" time="0.094" classname="com.testngexample.Sample6">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testngexample.Sample6.test1() didn&#039;t finish within the time-out 5">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testngexample.Sample6.test1() didn't finish within the time-out 5
at java.lang.Thread.interrupt0(Native Method)
at java.lang.Thread.interrupt(Unknown Source)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:60)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:38)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test1 -->
</testsuite> <!-- com.testngexample.Sample6 -->
